### ISSUE TITLE
Support invert draw mode (aka. fix rendering issues in Asteroids)

### ISSUE THREAD

**Issue by jbmorley** [inseven/opolua#121]
![asteroids](https://user-images.githubusercontent.com/220887/154822070-64b1dbfc-6d01-48ad-b791-75f9deadd1b9.png)

**Comment by jbmorley** [comment]
Pushing to Future as, while it looks a bit rough, we're not going to get all the interpreter issues fixed in v1.

**Comment by jbmorley** [comment]
Related to #30.

**Comment by jbmorley** [comment]
Looks like we're also seeing these issues in Super Breakout.

**Comment by tomsci** [comment]
Much better now.
![image](https://github.com/inseven/opolua/assets/2305420/834f3119-9b0c-4a49-abea-19f8fd2e4d52)

**Comment by jbmorley** [comment]
🎉👾🛸
