### ISSUE TITLE
Monitoring large directory structures / open-in-place locations can cause crashes

### ISSUE THREAD

**Issue by jbmorley** [inseven/opolua#130]
It looks like we're opening too many file handles (one for each directory we're monitoring). We should double check that we've not got a bug which fails to close them when we stop monitoring and, if not, we should look at options to reduce the impact of adding large directories.

The best ideas I have for this right now include:

1. using a shared manager that ensures we never a directory more than once (right now we'll observe the full directory tree once for every view pushed on the stack)
2. specify a maximum number of directories after which a given monitor will simply give up
3. specify a maximum directory depth (e.g., only observe 3 sub-directories deep, etc)
4. track the open file handles and have a shared limit after which we give up

Obviously options 2-4 are pretty bad as they will all lead to a degraded user experience. If we have to go down this route, we might want to inform the user. Equally, it might be sufficient to require the user to reload a directory in this scenario. Perhaps we can add a manual pull-to-refresh mechanism which will both refresh the current directory and trigger the forced iCloud download.

**Comment by jbmorley** [comment]
Oddly this _seems_ to be manifesting in a really weird way where the Lua interpreter is failing to read some of its scripts. Is Lua perhaps leaving file handles open too?

**Comment by tomsci** [comment]
> the Lua interpreter is failing to read some of its scripts. Is Lua perhaps leaving file handles open too?

All the Lua modules are loaded via [FileManager](https://github.com/inseven/opolua/blob/f3902c051d247a0ee0e60634f37c14e41c255047/swift/OpoInterpreter.swift#L79) so it doesn't ever have any of its own file handles to manage. So I don't think it'll be adding to the problem, but of course if you're hitting ulimits then modules might fail to load too.

**Comment by jbmorley** [comment]
I've done a bunch of work to improve the directory monitoring in #141. Unfortunately this still isn't a perfect solution as we can guarantee that we'll run out of file handles if users add _really_ big directories. We should, at the very least, fail gracefully and _not_ crash if we're using too many file handles. Perhaps in that scenario, we can just leave the user to manually update (pull-to-refresh)?

**Comment by jbmorley** [comment]
Closing this in lieu of #178.
