### ISSUE TITLE
Show all program icons in monochrome when using the Series 5 theme

### ISSUE THREAD

**Issue by jbmorley** [inseven/opolua#148]

**Comment by tomsci** [comment]
Not convinced about this tbh - right now having a colour icon is the only indication that an app supports colour, so being heavy handed with the theming actively removes information about your apps..

**Comment by jbmorley** [comment]
Pushing into future for later consideration.

**Comment by jbmorley** [comment]
On further thought, I think I'm happy to close this as won't fix for the time being.
