### ISSUE TITLE
mPOPUP needs to support adding scrollbars if necessary

### ISSUE THREAD

**Issue by tomsci** [inseven/opolua#156]
Massive menus like this render with a vertical scrollbar on the Series 5

![image](https://user-images.githubusercontent.com/2305420/152524525-311170ed-5f09-4d7b-bcc9-a26ab87ebae2.png)

**Comment by tomsci** [comment]
With #287:
![image](https://github.com/inseven/opolua/assets/2305420/c8da4432-6d4f-45e7-b790-c3d247d4208d)

**Comment by kapfab** [comment]
This is also true for mCARD and mCASC AFAIK.

**Comment by tomsci** [comment]
> There are some redraw issues with menus that have both scrollbars and dividing lines in them

These issues should be addressed in #288.
