### ISSUE TITLE
Screen border draws over the actual screen area

### ISSUE THREAD

**Issue by tomsci** [inseven/opolua#166]
For example:

![image](https://user-images.githubusercontent.com/2305420/152592400-baa09168-5f37-4155-9139-1cae15cced68.png)

Patching out the screen border shows how that app is supposed to display:

![image](https://user-images.githubusercontent.com/2305420/152592505-a1c9aa24-bb46-4c01-a595-ced147799726.png)

**Comment by jbmorley** [comment]
Fixed in ec6e6b823e0480df7a0f9b43122c882c1a72dae9.
