### ISSUE TITLE
Unimplemented Operation: opx.systinfo.SIKeyClickEnabled

### ISSUE THREAD

**Issue by jbmorley** [inseven/opolua#170]
Unimplemented operation opx.systinfo.SIKeyClickEnabled
INVADERS\START:00000CF4: FF [NextOpcodeTable] 18 CallOpxFunc 2 21 (systinfo SIKeyClickEnabled)
TOOLBAR\TBARLINK: [Lua] toolbar.lua:64
INVADERS\TOOLBARSTART:00000076: 53 [RunProcedure] 0x0012 (name="TBARLINK" nargs=1)
stack traceback:
	[C]: in function 'error'
	init.lua:443: in function 'unimplemented'
	systinfo.lua:165: in function 'opx.systinfo.SIKeyClickEnabled'
	ops.lua:2294: in function 'ops.CallOpxFunc'
	ops.lua:2180: in function 'ops.NextOpcodeTable'
	runtime.lua:806: in function <runtime.lua:791>
	[C]: in function 'xpcall'
	runtime.lua:923: in method 'pcallProc'
	runtime.lua:963: in method 'callProc'
	toolbar.lua:64: in field 'fn'
	runtime.lua:319: in method 'pushNewFrame'
	ops.lua:976: in function 'ops.RunProcedure'
	runtime.lua:806: in function <runtime.lua:791>
	[C]: in function 'xpcall'
	runtime.lua:923: in method 'pcallProc'
	runtime.lua:1278: in function 'runtime.runOpo'

**Comment by tomsci** [comment]
Fixed in 34d9ca845dd027db8c8e9aa1db4a08a3655148f6
