### ISSUE TITLE
SourceViewController does the notch thing (incorrect content insets)

### ISSUE THREAD

**Issue by tomsci** [inseven/opolua#173]
![image](https://user-images.githubusercontent.com/2305420/152678992-e6b25020-d5cd-43c1-b670-795e2537bd09.png)

**Comment by jbmorley** [comment]
Oh balls.

**Comment by jbmorley** [comment]
Fixed in abb6ed7dba1b17a16f9100d55236edfc79250cdd. This solution feels pretty icky.
