### ISSUE TITLE
Crash with missing call stack when browsing through directories

### ISSUE THREAD

**Issue by jbmorley** [inseven/opolua#191]
<img width="1792" alt="Screenshot 2022-02-11 at 11 18 16" src="https://user-images.githubusercontent.com/220887/153672764-9051e864-4287-444d-8127-97cacced9117.png">

Perhaps something in our Lua code is failing to handle an error?

**Comment by tomsci** [comment]
I've checked through `func recognize(path:)` and `func getFileInfo(path:)` and they look fine in terms of error handling. I'm more inclined to think this might be a threading issue where this `OpoInterpreter` instance is being used by multiple threads concurrently?

**Comment by jbmorley** [comment]
I don't believe we're sharing the interpreter between threads anymore but I'll keep an eye open for that.

**Comment by jbmorley** [comment]
I don't think I've ever seen this on device. Perhaps it's some weird simulator bug? I would feel deeply uncomfortable with that explanation, but the lack of on-device repro is nudging me towards pushing it out into Future.

**Comment by jbmorley** [comment]
Pushing this into Future; we can bring it back if we get a repro.

**Comment by jbmorley** [comment]
Closing as invalid. I've not seen this issues on target. We can always re-open or raise a new issue if we see this again.
