### ISSUE TITLE
Support databases

### ISSUE THREAD

**Issue by jbmorley** [inseven/opolua#203]
Right now we don't support databases--the EPOC data format is gnarly. Unfortunately they were very easy to use in OPL so many programs make use of them and at some point we'll want to try adding support again. This issue is intended to track the work and capture programs we know require database support.

**Comment by jbmorley** [comment]
LogJam by Adam's Software (/library/epocgames/logjam).

**Comment by jbmorley** [comment]
@kapfab For sure. I'll try to page it back in and write it up.

**Comment by jbmorley** [comment]
https://web.archive.org/web/20041130063903/http://home.t-online.de/home/thomas-milius/Download/Documentation/EPCDB.htm

**Comment by tomsci** [comment]
While initial work on supporting databases is now merged, there is doubtless a long tail of minor parsing issues to be addressed. These should be raised as separate issues.
