### ISSUE TITLE
Android version 

### ISSUE THREAD

**Issue by splash3313** [inseven/opolua#253]
Issue is that there is no Android version

**Comment by frantek** [comment]
Also wondering the same thing. Seems like an odd choice just to build for iOS, when Android is the most used OS in the world and can run on multiple platforms and emulations

**Comment by jbmorley** [comment]
Hi! Thanks for your feedback and interest.

Android's generally been a non-goal as the ability to sideload and more permissive Play Store rules mean it's already really well served when it comes to emulators while, on iOS, Game Play Color genuinely brings something new. I'm also the sole developer and only able to put a small amount of time into the project (it doesn't pay the bills), so I've generally viewed the huge variety of Android devices as an unwelcome distraction. Also, I don't even own an Android phone to test on. 😅

That's not to say I'm not open to something in the future–I've got a branch which adds basic Android support from a couple of years ago when I played around with a Pixel–but I'd love to figure out a way to produce (and sustain) something less bare-bones before I ship it.

**Comment by jbmorley** [comment]
OK. So let's try that again.

Hi! Thank you for the feedback. 😊

Android is definitely something we could support in the future (we'll keep the issue open), but neither @tomsci nor I are Android users, so we're unlikely to get to it anytime soon–if nothing else, we don't have devices to test on. Unfortunately, an Android port would represent a significant amount of work; while the core is written in Lua, the scheduler, window server, etc, are all written in Swift and _very_ iOS specific (roughly 50% of the code is iOS-targeted Swift).

That said, I totally get it. And seeing OpoLua on a Planet Computers device would be very satisfying.

**Comment by jbmorley** [comment]
Closing as won't fix.
