### ISSUE TITLE
Issue with the `NotFloat` function in `ops.lua`

### ISSUE THREAD

**Issue by kapfab** [inseven/opolua#262]
Given the weirdness of OPL logical operators with floats, I don’t think many programs actually make use of this opcode, but the function `NotFloat` in `ops.lua` should be:
```
function NotFloat(stack) -- 0x66
    stack:push(stack:pop() == 0)
end
```
instead of:
```
function NotFloat(stack) -- 0x66
    stack:push(stack:pop() ~= 0)
end
```

**Comment by tomsci** [comment]
Thanks for the report! Yep that seems backwards.
