### ISSUE TITLE
Unable to add folders on macOS

### ISSUE THREAD

**Issue by jbmorley** [inseven/opolua#277]
I've disabled the ability to install the iPad builds on Macs but it might be something to look at in the future.

**Comment by kapfab** [comment]
I was nice to have OpoLua running on my Mac. Why should we remove macOS support just for such a minor issue?
I’ll be happy to investigate, have you already had some time to take a look at it?

**Comment by jbmorley** [comment]
@kapfab Thanks for the quick feedback. We didn't have Apple Silicon Macs during development and it slipped through the cracks–I don't like to release software I'm not able to personally test. Having finally upgraded I noticed it was supported and tried it out, only to find out this (to me at least) key feature caused the app to crash.

I don't really have time to prioritize this right now but I'm definitely open to suggestions. My guess is it's down to the fact that iOS and macOS interact with the file system and sandbox in fundamentally different ways and we'd need to have a dedicated macOS path for managing folders. At least that's what I've found myself doing with other projects.

**Comment by kapfab** [comment]
OK. I’ll try to find some time to see if that can be addressed easily.

**Comment by jbmorley** [comment]
Thanks. I look forward to your feedback. I'll take a look myself if I get time, but the list is long right now. 😅

**Comment by kapfab** [comment]
Sure. I’d really like to help on database support (which is my most-wanted feature) but there doesn’t seem to be any documentation available for EPOC.

**Comment by jbmorley** [comment]
> Sure. I’d really like to help on database support (which is my most-wanted feature) but there doesn’t seem to be any documentation available for EPOC.

Yeah. I guess this is really a discussion for #203 but it's one I'd love to get to the bottom of too. I spent a multi-hour flight brute-forcing the problem with some experimental Python cloning some EPOC code I found and managed to get what felt like half-way through but then never found the time to get back to it.

**Comment by jbmorley** [comment]
@kapfab How were you installing software on macOS? If there's a workflow that works for the Mac already then we can just disable the add folder button when running on a Mac and run with that. Which OS are you using it on?

**Comment by kapfab** [comment]
SIS files automatically open with OpoLua, which installs them nicely.

**Comment by jbmorley** [comment]
@kapfab Awesome! I didn't think to try that. 🫠

I've re-enabled macOS for the time being and in the short term I'll guard against this crash.

**Comment by kapfab** [comment]
Great!
On my side, I don’t get a crash when trying to add a folder, I just get an error message (`The file couldn’t be saved.`).

**Comment by tomsci** [comment]
> SIS files automatically open with OpoLua

I had totally forgotten we added support for that :D
