### ISSUE TITLE
Internal Error: database.lua:435: Set bit found with previous bit unset!

### ISSUE THREAD

**Issue by jbmorley** [inseven/opolua#329]
## Description

- ClockP (https://archive.org/download/3-libjune-05/3LIBJUNE05.iso/library%2Fepocgames%2Fclockp%2FClockP.sis)

## Details

```
database.lua:435: Set bit found with previous bit unset!
CLOCKP\MAIN:00000301: B4 [Open] logName=11 fields=LAN$
stack traceback:
	[C]: in function 'assert'
	database.lua:435: in function <database.lua:373>
	(...tail calls...)
	runtime.lua:628: in method 'openDb'
	ops.lua:1587: in function 'ops.Open'
	runtime.lua:859: in function <runtime.lua:844>
	[C]: in function 'xpcall'
	runtime.lua:978: in method 'pcallProc'
	runtime.lua:1242: in function 'runtime.runOpo'
```

**Comment by tomsci** [comment]
Excellent, well that answers the question of can you get gaps in that bitset...

**Comment by tomsci** [comment]
Actually this error is due to misparsing section 7 as a data section (it isn't), so I think it's probably still true that you shouldn't have gaps in the datasetBitmask.

**Comment by tomsci** [comment]
Now fixed on tomsci-database branch
