### ISSUE TITLE
Big databases are weird

### ISSUE THREAD

**Issue by jbmorley** [inseven/opolua#331]
## Description

- Periodic (https://archive.org/download/3-libjune-05/3LIBJUNE05.iso/library%2Fepocmisc%2Fperiodic%2FPeriodic.sis)

## Details

```
database.lua:386: bad argument #2 to 'unpack' (data string too short)
PERIODIC\MAIN:00000390: B4 [Open] logName=11 fields=LAN$
stack traceback:
	[C]: in function 'string.unpack'
	database.lua:386: in function <database.lua:373>
	(...tail calls...)
	runtime.lua:628: in method 'openDb'
	ops.lua:1587: in function 'ops.Open'
	runtime.lua:859: in function <runtime.lua:844>
	[C]: in function 'xpcall'
	runtime.lua:978: in method 'pcallProc'
	runtime.lua:1242: in function 'runtime.runOpo'
```

**Comment by tomsci** [comment]
DBs with lots of modifications (which periodic.rsc has) reuse old parts of the file for data sections and I haven't figured out how you parse that because they appear to blat over the section metadata.

**Comment by tomsci** [comment]
Now fixed on `tomsci-database` branch
