### ISSUE TITLE
`Async.Request` has unnecessary optional files

### ISSUE THREAD

**Issue by jbmorley** [inseven/opolua#34]
Perhaps it would be better to make greater use of enums with associated types?

**Comment by tomsci** [comment]
I refactored RequestType to use an associated type enum a couple of days ago - what "optional files" are you referring to?

**Comment by jbmorley** [comment]
I missed that. Will take a look. 👌🏻

**Comment by jbmorley** [comment]
Based on Tom's comments, I'm going to close this as won't fix. We can make tweaks if we see anything that actually needs changing.
