### ISSUE TITLE
Remove `BinaryDatabaseError`

### ISSUE THREAD

**Issue by jbmorley** [inseven/opolua#395]
I've noticed that we've still got a custom error—`BinaryDatabaseError`—that we're special-casing when our failing operation is 'database.loadBinary'. I imagine we don't need this any more now that we've got database support. Can we remove it?

https://github.com/inseven/opolua/blob/974ee1d9f8507808e90455eae99c60105a45f2ee/swift/OpoInterpreter.swift#L683

**Comment by tomsci** [comment]
Yep we will never throw `database.loadBinary` any more, so `BinaryDatabaseError` can have the 🔥
