### ISSUE TITLE
[FreeNote] Unimplemented Operation: fns.Week

### ISSUE THREAD

**Issue by kapfab** [inseven/opolua#438]
## Description

Error at launch

## Metadata

| Key | Value |
| --- | --- |
| **Title** | FreeNote |
| **Source URL** | https://archive.org/download/3-libjune-05/3LIBJUNE05.iso/library%2Fepocmisc%2Ffreenote%2FFreeNote.SIS |

## Details

```
Unimplemented operation fns.Week
FREENOTE\GETTODAY:00003F84: 57 [CallFunction] 0x20 (Week)
FREENOTE\FREENOTE:00000CD7: 53 [RunProcedure] 0x092B (name="GETTODAY" nargs=0)
stack traceback:
	[C]: in function 'error'
	init.lua:485: in function 'unimplemented'
	fns.lua:509: in function 'fns.Week'
	ops.lua:1032: in function 'ops.CallFunction'
	runtime.lua:884: in function <runtime.lua:869>
	[C]: in function 'xpcall'
	runtime.lua:1003: in method 'pcallProc'
	runtime.lua:1290: in function 'runtime.runOpo'
```

**Comment by tomsci** [comment]
I've pushed a fix for `WEEK()` but haven't been able to test the app today due to the issues with archive.org, so it might immediately fall over with some other problem!
