### ISSUE TITLE
[MBornes5] Graphics rendering glitch

### ISSUE THREAD

**Issue by kapfab** [inseven/opolua#444]
## Description

Opolua does not behave like a real device for a specific graphics rendering operation.

## Metadata

| Key | Value |
| --- | --- |
| **Title** | MBornes5 |
| **Source URL** | https://archive.org/download/3-libjune-05/3LIBJUNE05.iso/library/epocgames/millesbournes/MBornes5.SIS |

## Details

When the last card of the player’s hand (the one at the bottom) is discarded, it should disappear (other cards are just blanked).
That’s what happens on a real device.
With Opolua, this last card does not disappear when discarded: it's sent behind the other cards and stays visible (see screenshot).

This behaviour makes me think of `gRANK` or `gORDER` making use of an incorrect drawable position (z-index), maybe just shifted by 1, but this might be something else.

![MBornes5_Glitch](https://github.com/user-attachments/assets/c19313a2-e843-45bd-9602-573ddce46cc2)

**Comment by tomsci** [comment]
Thanks for the report. Looking at the code there is a potential off-by-one error due to the toolbar clock widget, which internally is treated like another window but shouldn't be considered by the window positioning calculations. That might be the cause.

**Comment by kapfab** [comment]
Good news, this will probably benefit a few other programs!

**Comment by jbmorley** [comment]
@kapfab Seems like these kinds of oddities would be great to record in some OPL-level documentation. 🤔
