### ISSUE TITLE
Compiler: missing support for CANCEL, IOSIGNAL, POINTERFILTER?

### ISSUE THREAD

**Issue by kapfab** [inseven/opolua#462]
Looking at the compiler code, it seems that the following EPOC32 keywords are not handled:
- CANCEL
- IOSIGNAL
- POINTERFILTER

**Comment by tomsci** [comment]
I swear, every time I think I’ve gone through the whole list…

**Comment by kapfab** [comment]
Hehe. The list of OPL opcodes is such a mess…
I’ve compared with my own referential, it should be comprehensive (for EPOC32) with these 3 additions.
I’ll now compare the return value types and number of parameters for each command and their data types.
