### ISSUE TITLE
Compiler: possible discrepancies with some opcodes

### ISSUE THREAD

**Issue by kapfab** [inseven/opolua#465]
I compared how opcodes are defined in OpoLua with my own opcodes reference and I found a few discrepancies:
- `CLEARFLAGS` (missing `flags&` parameter)
- `DATIMSTR` (extraneous parameter)
- `dEDITMULTI` (first parameter is an address — long for EPOC32, integer for SIBO)
- `LOC` (number of parameters can be 3, 4 or 5)
- `MAX`/`MEAN`/`MIN`/`STD`/`SUM`/`VAR` (minimum number of parameters is 1 in variadic mode)
- `mPOPUP` (minimum number of parameters is 5)
- `PEEKB`/`PEEKW` (an integer is returned, not an address)

**Comment by kapfab** [comment]
(I haven't checked if these issues only concern the compiler or also the OpoLua interpreter.)

**Comment by tomsci** [comment]
Thanks for such a detailed analysis.

> CLEARFLAGS (missing flags& parameter)

Yep, compiler bug. Interpreter doesn't support `ClearFlags` opcode so no implementation means no bug :)

> DATIMSTR (extraneous parameter)

Compiler bug. Interpreter looks correct.

> dEDITMULTI (first parameter is an address — long for EPOC32, integer for SIBO)

dEDITMULTI didn't exist on SIBO did it? So I think the current definition in complier.lua is reasonable? While we're here though, the docs say the last parameter is `maxLength%` but it is fact a long according to my S5's compiler (and the ER6-era OPL source code). compiler.lua correctly types this but doesn't document that it's a deviation from the docs, so I'll update that.

> LOC (number of parameters can be 3, 4 or 5)

Are you sure? Every reference I have has `a% = LOC(a$, b$)`

> MAX/MEAN/MIN/STD/SUM/VAR (minimum number of parameters is 1 in variadic mode)

We will catch that if written as `MAX()` but `MAX` on its own will cause an internal error, I'll fix that.

> mPOPUP (minimum number of parameters is 5)

Variadic functions, the bane of every type system :)

> PEEKB/PEEKW (an integer is returned, not an address)

Yep, thanks.

**Comment by kapfab** [comment]
> dEDITMULTI didn't exist on SIBO did it? So I think the current definition in complier.lua is reasonable?

It’s EPOC/SymbianOS only, so it works fine as it is. It was just to have the same type for addresses across all keywords.

> While we're here though, the docs say the last parameter is maxLength% but it is fact a long according to my S5's compiler (and the ER6-era OPL source code). compiler.lua correctly types this but doesn't document that it's a deviation from the docs, so I'll update that.

Yep, it’s definitely a long.

> Are you sure? Every reference I have has a% = LOC(a$, b$)

Sorry, it’s a typo! I meant `IOC`, not `LOC`.

**Comment by tomsci** [comment]
> It was just to have the same type for addresses across all keywords

Ah I see your point. Yes I was debating renaming `SiboInt` anyway since it's not the most obvious name.

>  I meant IOC, not LOC

gotcha.
