### ISSUE TITLE
The bottom toolbar buttons cannot be pressed on the Series 7

### ISSUE THREAD

**Issue by jbmorley** [inseven/opolua#77]
Pressing the 5th toolbar buttons onwards toggles the clock instead.

![IMG_0230](https://user-images.githubusercontent.com/220887/150892295-28201f63-73f1-4d09-b409-7c665d5242bc.jpeg)

**Comment by tomsci** [comment]
Right, the toolbar API in the Psion 5 release only supported 4 buttons and the clock is given a pseudo id of 5. I'll make it use a larger id...

**Comment by jbmorley** [comment]
@tomsci fixed this! 🎉
